server:
  port: 8083
  servlet:
    context-path: /arepas-21

spring:
  application:
    name: arepas-21

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
    username: postgres.elppuzaymcysqklvamss
    password: G8nz4L3Zn9**
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: K8#mP$9xQ2vB&nL7wR@3jY6tE5uI0pA4sF1dH8cG9bN2mX7zV5qW3eR6yT0uI9oL4kJ
  expiration: 86400000
    
logging:
  level:
    com.restaurante.arepas21.config.security: DEBUG
    org.springframework.security: DEBUG

