server:
  port: 8083
  servlet:
    context-path: /arepas-21

spring:
  application:
    name: arepas-21

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres
    username: postgres.elppuzaymcysqklvamss
    password: G8nz4L3Zn9**
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 0E4YlDC85HM1Tt8aZl4nCuPlzkXznle2fiYyaaPq6Hw=
  expiration: 36000000
    
logging:
  level:
    com.restaurante.arepas21.config.security: DEBUG
    org.springframework.security: DEBUG

